# Generated by Django 4.1.3 on 2022-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('packet_transmit', models.IntegerField()),
                ('packet_receive', models.IntegerField()),
                ('packet_loss_rate', models.FloatField()),
                ('packet_loss_count', models.IntegerField()),
                ('rtt_min', models.FloatField()),
                ('rtt_avg', models.FloatField()),
                ('rtt_max', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
