# Generated by Django 4.1.3 on 2022-12-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ping',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='ping',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
